"""Compile IR intents to native Rego for each enforcement surface.

The same code path also emits *drifted* variants (``Mutation``): one predicate on one
surface is rewritten the way a hand edit typically goes wrong. The benchmark uses these
to measure which testing strategy notices the drift.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from .ir import Intent, Pred
from .model import ATTRS, SURFACES, Binding

MUTATIONS = {
    "negate": "comparison inverted (== vs !=, in vs not in, >= vs <)",
    "drop": "predicate deleted",
    "case_fold": "case-insensitive comparison where the intent is exact",
    "prefix": "startswith() instead of equality (registry spoofing)",
    "off_by_one": "strict instead of inclusive bound",
    "fail_open": "written as 'not violated', so an absent attribute passes",
    "string_bool": 'bool compared with "true" (or string with true)',
    "wrong_path": "attribute read from a plausible but wrong field",
    "allowlist_extra": "allowlist gained one extra value",
}
NEGATE = {"eq": "ne", "ne": "eq", "in": "not_in", "not_in": "in", "le": "gt", "ge": "lt",
          "is_true": "is_false", "is_false": "is_true"}
SYM = {"eq": "==", "ne": "!=", "le": "<=", "ge": ">=", "lt": "<", "gt": ">"}


@dataclass(frozen=True)
class Mutation:
    part: str  # "scope" | "require"
    index: int
    op: str  # key of MUTATIONS


def _lit(v) -> str:
    return json.dumps(v)


def _set(values) -> str:
    return "{" + ", ".join(_lit(v) for v in sorted(values)) + "}"


def _extra(p: Pred):
    return next((v for v in ATTRS[p.attr].domain if v not in p.value), None)


def applicable(p: Pred) -> list[str]:
    t = ATTRS[p.attr].type
    ops = ["negate", "drop", "fail_open", "wrong_path"]
    if t == "str" and p.op in ("eq", "ne", "in", "not_in"):
        ops.append("case_fold")
    if t == "str" and p.op in ("eq", "in"):
        ops.append("prefix")
    if p.op in ("le", "ge"):
        ops.append("off_by_one")
    if p.op in ("is_true", "is_false"):
        ops.append("string_bool")
    if p.op == "in" and _extra(p) is not None:
        ops.append("allowlist_extra")
    return ops


def _body(p: Pred, b: Binding, mut: str | None = None) -> list[str]:
    a = b.expr.format(b.wrong_path if mut == "wrong_path" else b.path)
    op, value = p.op, p.value
    if mut == "negate":
        op = NEGATE[op]
    if mut == "off_by_one":
        op = {"le": "lt", "ge": "gt"}[op]
    if mut == "allowlist_extra":
        value = value + (_extra(p),)
    if op in ("is_true", "is_false"):
        as_str = (b.kind == "strbool") != (mut == "string_bool")
        want = "true" if op == "is_true" else "false"
        return [f"{a} == {_lit(want) if as_str else want}"]
    if mut == "case_fold":
        a = f"lower({a})"
        value = tuple(v.lower() for v in value) if isinstance(value, tuple) else value.lower()
    if op == "in":
        if mut == "prefix":
            return [f"some allowed in {_set(value)}", f"startswith({a}, allowed)"]
        return [f"{a} in {_set(value)}"]
    if op == "not_in":
        return [f"x := {a}", f"not x in {_set(value)}"]
    if mut == "prefix":
        return [f"startswith({a}, {_lit(value)})"]
    return [f"{a} {SYM[op]} {_lit(value)}"]


def _fn(name: str, body: list[str]) -> str:
    return f"{name}(o) if {{\n" + "".join(f"\t{line}\n" for line in body) + "}\n"


def _rules(name: str, p: Pred, b: Binding, mut: str | None) -> list[str]:
    if mut == "fail_open":
        violated = _body(Pred(p.attr, NEGATE[p.op], p.value), b)
        return [_fn(f"{name}_violated", violated), _fn(name, [f"not {name}_violated(o)"])]
    return [_fn(name, _body(p, b, mut))]


def _conj(name: str, parts: list[str]) -> str:
    return _fn(name, [f"{n}(o)" for n in parts]) if parts else f"{name}(_) := true\n"


def module(intent: Intent, surface: str, package: str, mutation: Mutation | None = None) -> str:
    s = SURFACES[surface]
    out = [f"package {package}\n", "import rego.v1\n",
           f"# intent {intent.id}: {intent.title}\n# generated by policy-synapse; edit intents/intents.json instead\n",
           f"subjects := {s.subjects}\n"]
    names: dict[str, list[str]] = {}
    for part, preds in (("scope", intent.scope), ("require", intent.require)):
        names[part] = []
        for i, p in enumerate(preds):
            mut = mutation.op if mutation and (mutation.part, mutation.index) == (part, i) else None
            if mut == "drop":
                continue
            names[part].append(f"{part}_{i}")
            out += _rules(f"{part}_{i}", p, s.bindings[p.attr], mut)
    out += [_conj("in_scope", names["scope"]), _conj("compliant", names["require"])]
    if s.decision == "allow":
        out += ["default allow := false\n",
                "allow if {\n\tsome o in subjects\n\tnot in_scope(o)\n}\n",
                "allow if {\n\tsome o in subjects\n\tcompliant(o)\n}\n"]
    else:
        head = "deny contains msg" if s.decision == "deny" else 'violation contains {"msg": msg}'
        msg = _lit(f"{intent.id}: {intent.title}")
        out.append(f"{head} if {{\n\tsome o in subjects\n\tin_scope(o)\n\tnot compliant(o)\n\tmsg := {msg}\n}}\n")
    return "\n".join(out)


def _gatekeeper_names(intent: Intent) -> tuple[str, str]:
    kind = "K8s" + "".join(w.capitalize() for w in intent.id.split("-"))
    return kind.lower(), kind


def constraint_template(intent: Intent) -> str:
    name, kind = _gatekeeper_names(intent)
    rego = "".join(f"        {line}\n" if line else "\n" for line in module(intent, "admission", name).splitlines())
    return (f"apiVersion: templates.gatekeeper.sh/v1\nkind: ConstraintTemplate\nmetadata:\n  name: {name}\n"
            f"spec:\n  crd:\n    spec:\n      names:\n        kind: {kind}\n"
            f"  targets:\n    - target: admission.k8s.gatekeeper.sh\n      rego: |\n{rego}"
            f"---\napiVersion: constraints.gatekeeper.sh/v1beta1\nkind: {kind}\nmetadata:\n  name: {intent.id}\n"
            f'spec:\n  match:\n    kinds:\n      - apiGroups: ["apps"]\n        kinds: ["Deployment"]\n')


def compile_all(intents: list[Intent], out: Path) -> Path:
    entries = []
    for i in intents:
        for s in i.surfaces:
            pkg = _gatekeeper_names(i)[0] if s == "admission" else f"policy_synapse.{s}.{i.id.replace('-', '_')}"
            f = out / s / f"{i.id}.rego"
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text(module(i, s, pkg), encoding="utf-8", newline="\n")
            if s == "admission":
                f.with_suffix(".yaml").write_text(constraint_template(i), encoding="utf-8", newline="\n")
            entries.append({"intent": i.id, "surface": s, "file": f"{s}/{i.id}.rego",
                            "decision": SURFACES[s].decision})
    manifest = out / "policies.json"
    manifest.write_text(json.dumps({"policies": entries}, indent=2) + "\n", encoding="utf-8", newline="\n")
    return manifest
